name: Auto-download resume from overleaf
description: Fetches a resume pdf from an overleaf and commits it to the repository.
author: sbrjt

inputs:
  overleaf_url:
    required: true
    description: Read-url from overleaf
  github_token:
    required: true
    description: GitHub token for authentication
  gdrive_link:
    description: Google drive link with edit permission
  gdrive_service_account_key:
    description: Service account JSON key string for Google Drive access
    required: false

runs:
  using: 'composite'
  steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Create requirements.txt
      run: |
        echo "selenium" > requirements.txt
        echo "google-api-python-client" >> requirements.txt
        echo "google-auth" >> requirements.txt
      shell: bash 

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.x
        cache: 'pip'

    - name: Install dependencies
      run: pip install -r requirements.txt
      shell: bash

    - name: Run Selenium script
      id: script
      run: python "${GITHUB_ACTION_PATH}/selenium_script.py" "${{ inputs.overleaf_url }}"
      shell: bash

    - name: Commit the PDF file
      id: set-output
      if: steps.script.outputs.skip != 'True'
      run: |
        # 1. Temporarily back up the newly compiled Overleaf resume files
        cp resume.pdf temp_resume.pdf
        cp resume.tex temp_resume.tex

        # 2. Reset the local repository to match the latest remote main commit
        git fetch origin main
        git reset --hard FETCH_HEAD

        # 3. Restore the new Overleaf files (overwriting the older versions)
        mv temp_resume.pdf resume.pdf
        mv temp_resume.tex resume.tex

        # 4. Configure Git and commit the changes
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"

        git add resume.tex resume.pdf
        git commit -m "Resume updated"
        git push origin HEAD:main
      env:
        GITHUB_TOKEN: '${{ inputs.github_token }}'
      shell: bash

    - name: Upload to google drive
      if: ${{ inputs.gdrive_link != '' && inputs.gdrive_service_account_key != '' && steps.script.outputs.skip != 'True'}}
      run: python "${GITHUB_ACTION_PATH}/upload_to_gdrive.py"
      env:
        GDRIVE_LINK: ${{ inputs.gdrive_link }}
        GDRIVE_SERVICE_ACCOUNT_KEY: ${{ inputs.gdrive_service_account_key }}
      shell: bash

branding:
  icon: 'book'
  color: 'green'
