name: Resume Syncer
on:
  workflow_dispatch:
  # schedule:
  #   - cron: '0 0 * * *'

permissions:
  contents: write

jobs:
  sync-resume:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: ./ # Uses action.yml in the root directory
        with:
          overleaf_url: ${{ secrets.OVERLEAF_URL }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

          # Optional: Google Drive sync configuration
          gdrive_link: ${{ secrets.GDRIVE_LINK }}
          gdrive_service_account_key: ${{ secrets.GDRIVE_SERVICE_ACCOUNT }}

          # Optional: Portfolio repository sync configuration
          portfolio_repo: ${{ secrets.PORTFOLIO_REPO }}
          portfolio_token: ${{ secrets.PORTFOLIO_TOKEN }}