name: Sync Overleaf Resume
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */4 * * *'

permissions:
  contents: write

jobs:
  sync-resume:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: ./ # Uses action.yml in the root directory
        with:
          overleaf_url: ${{ secrets.OVERLEAF_URL }}
          gdrive_link: ${{ secrets.GDRIVE_LINK }}
          gdrive_service_account_key: ${{ secrets.GDRIVE_SERVICE_ACCOUNT }}
          github_token: ${{ secrets.GITHUB_TOKEN }}


